name: Application fetch

description: Fetch an application.

uri:
  noun: application
  verb: manage

method: get

ttl: 0

security:
  processor: tokenAdmin
  meta:
    id: 1
    token:
      fragment: userToken

process:
  processor: account
  meta:
    id: 3
    application
      processor: varUri
      meta:
        id: 4
        index: 0
    name:
      processor: varUri
      meta:
        id: 5
        index: 1
    action: fetch
    token:
      fragment: userToken

fragments:
	- fragment: userToken
      meta:
        processor: varGet
          meta:
            id: 2
            name: token

