name: Application create

description: Create an application.

uri:
  noun: application
  verb: manage

method: post

ttl: 0

security:
  processor: tokenAdmin
  meta:
    id: 1
    token:
      processor: varPost
      meta:
        id: 2
        name: token

process:
  processor: datagatorApplication
  meta:
    id: 3
    accountName:
      processor: varPost
      meta:
        id: 4
        name: accountName
    applicationName:
      processor: varPost
      meta:
        id: 5
        name: applicationName
