name: Application fetch

description: Fetch an application.

application: Datagator

uri:
  noun: application
  verb: manage

method: get

ttl: 0

security:
  processor: TokenSysAdmin
  meta:
    id: 1
    token:
      processor: varGet
      meta:
        id: 2
        name: token

process:
  processor: datagatorApplication
  meta:
    id: 3
    applicationName:
      processor: varGet
      meta:
        id: 5
        name: applicationName
