name: Swagger import

description: Create resource/s from a Swagger document.
uri:
  noun: swagger
  verb: yaml

method: post

ttl: 0

security:
  processor: tokenDeveloper
  meta:
    id: 1
    token:
      processor: varGet
      meta:
        id: 2
        name: token

process:
  processor: resourceSwagger
  meta:
    id: 3
    resource: resource
